// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Bhumchu",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "Bhumchu",
            targets: ["AppModule"],
            bundleIdentifier: "com.askbhumchu.org.Bhumchu",
            teamIdentifier: "L42649D7LD",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [],
            path: ".",
            resources: [
                .process("Ask.gif"),
                .process("bhumchutalk.mp4"),
                .process("bhumchuintro.mp4"),
                .process("bhumchuplay.mp4"),
                .process("bhumchuread.mp4"),
                .process("bhumchusleeping.mp4"),
                .process("bhumchutickle.mp4"),
                .process("bhumchueat.mp4"),
                .process("cloud")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)